[defrost]
auto_enabled=true
auto_time1_min=360
auto_time2_min=1200
max_defr_time_min=30

[device]
serial=SN-65468
software_type=3
secret=F2AB391C

[app]
language=de

[reclaim]
reclaim_email=kvalita@gastro.cz
custom_email=MeineEmail@email.cz
order_number=xx-123456-abcd
obp_number=OBP-0012345 / VNE 1234567

[qr]
tutorial_url=https://servicedesk.gastro.cz

[service]
pin=12345

[lock]
pin=1234
auto_enabled=false

[sensors]
sensor1_id=28-062543ba0804
sensor1_offset=0
sensor2_id=28-0625424fb44e
sensor2_offset=0
sensor3_id=28-0625428c047e
sensor3_offset=0.0
sensor4_id=28-0625436ee4a0
sensor4_offset=0.0
sensor5_id=28-0b244021acde
sensor5_offset=0.0
sensor6_id=28-062542df7b4c
sensor6_offset=0
